name: Build F Prime Nightly Cache

on:
  workflow_dispatch:
  # schedule:
  #   # Run at 2 AM UTC every day
  #   - cron: '0 2 * * *'

jobs:
  build-fprime-cache:
    uses: ./.github/workflows/template-build-fprime.yml
    with:
      tag: nightly
      fprime-branch: devel
